name: nexus_frontend
description: Frontend für das Nexus-Backend mit Wissensvisualisierung und Suche.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  # Netzwerk und API
  dio: ^5.3.2
  json_annotation: ^4.8.1
  # Authentifizierung und Sicherheit
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  # UI Komponenten
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  # Wissensvisualisierung
  graphview: ^1.2.0
  flutter_animate: ^4.2.0
  # Lokale Datenspeicherung
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Sonstiges
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#2c3e50"
  image: assets/icons/splash_icon.png 