global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'insight-synergy'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 5s

  - job_name: 'api-health'
    metrics_path: /api/health
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s 